site_name: 极光文档
site_author: JiGuang Offical
site_url: https://docs.jiguang.cn/
repo_url: https://github.com/jpush/jpush-docs/
site_favicon: img/favicon.ico
site_description: JPush, JMessage, 极光推送, 极光IM, Android Push, Android 推送, 安卓推送, iOS Push, APNs, Push Notification
copyright: Copyright 2011-2017, jiguang.cn, All Rights Reserved. <br />粤ICP备12056275号-13 深圳市和讯华谷信息技术有限公司
theme: 'mkdocs'
theme_dir: 'zh/themes/jiguang'
docs_dir: zh
extra_css: []
extra_javascript: []
extra_templates: []


pages:

- home: 'index.md'

- JPush:

  - 入门指南:
    - 'JPush 产品简介': 'JPush/docs/guideline/intro.md'
    - '控制台使用指南': 'JPush/docs/console/Instructions.md'
    - 'JPush 短信补充': 'JPush/docs/guideline/push-SMS-intro.md'
    - 'Rich Push 开发指南': 'JPush/docs/advanced/rich_push.md'
    - '常见问题': 'JPush/docs/guideline/faq.md'
  - Android:
    - 'Android SDK 概述': 'JPush/docs/client/Android/android_sdk.md'
    - '3 分钟 Demo': 'JPush/docs/client/Android/android_3m.md'
    - 'Android SDK 集成指南': 'JPush/docs/client/Android/android_guide.md'
    - 'Android SDK 调试指南': 'JPush/docs/client/Android/android_debug_guide.md'
    - 'Android SDK 进阶教程': 'JPush/docs/client/Android/android_senior.md'
    - 'Android SDK API': 'JPush/docs/client/Android/android_api.md'
    - 'Android SDK FAQ': 'JPush/docs/client/Android/android_faq.md'
  - iOS:
    - 'iOS SDK 概述': 'JPush/docs/client/iOS/ios_sdk.md'
    - 'iOS SDK 集成指南': 'JPush/docs/client/iOS/ios_guide_new.md'
    - 'iOS SDK 调试指南': 'JPush/docs/client/iOS/ios_debug_guide.md'
    - 'iOS 证书设置指南': 'JPush/docs/client/iOS/ios_cer_guide.md'
    - 'iOS 新特性汇总': 'JPush/docs/client/iOS/ios_new_fetures.md'
    - 'iOS SDK API': 'JPush/docs/client/iOS/ios_api.md'
    - 'iOS SDK FAQ': 'JPush/docs/client/iOS/ios_faq.md'
  - WindowsPhone:
    - 'Windows Phone SDK 概述': 'JPush/docs/client/WindowsPhone/winphone_sdk.md'
    - 'Windows Phone 3 分钟 Demo': 'JPush/docs/client/WindowsPhone/winphone_3m.md'
    - 'Windows Phone SDK 集成指南': 'JPush/docs/client/WindowsPhone/winphone_guide.md'
    - 'Windows Phone API': 'JPush/docs/client/WindowsPhone/winphone_api.md'
  - REST API:
    - 'REST API 概述': 'JPush/docs/server/push/server_overview.md'
    - 'Push API v3': 'JPush/docs/server/push/rest_api_v3_push.md'
    - 'Report API v3': 'JPush/docs/server/push/rest_api_v3_report.md'
    - 'Device API v3': 'JPush/docs/server/push/rest_api_v3_device.md'
    - 'Schedule API v3': 'JPush/docs/server/push/rest_api_push_schedule.md'
    - 'HTTP 状态码': 'JPush/docs/server/push/http_status_code.md'
  - 高级:
    - 'JPush 应用场景': 'JPush/docs/advanced/scenes.md'
    - 'JPush 高级话题': 'JPush/docs/advanced/topics.md'
  - 客户端集成插件: 'JPush/docs/client/client_plugins.md'
  - 服务端 SDK:
    - 'Java SDK': 'JPush/docs/server/3rd/java_sdk.md'
    - 'Python SDK': 'JPush/docs/server/3rd/python_sdk.md'
    - 'PHP SDK': 'JPush/docs/server/3rd/php_sdk.md'
    - 'Ruby SDK': 'JPush/docs/server/3rd/ruby_sdk.md'
    - 'C# SDK': 'JPush/docs/server/3rd/csharp_sdk.md'
    - 'Node.js SDK': 'JPush/docs/server/3rd/nodejs_sdk.md'
  - 旧文档:
    - 'REST API v2 - Push': 'JPush/docs/server/old/rest_api_v2_push.md'
    - 'REST API v2 - Report': 'JPush/docs/server/old/rest_api_v2_report.md'
  - 最近更新: 'JPush/docs/updates.md'
  - 资源下载: 'JPush/docs/resources.md'

- JMessage:

  - 入门指南:
    - 'JMessage 产品简介': 'JMessage/docs/guideline/jmessage_guide.md'
    - '常见问题': 'JMessage/docs/guideline/faq.md'
  - Android:
    - 'SDK 开发指南': 'JMessage/docs/client/im_sdk_android.md'
    - 'SDK 集成指南': 'JMessage/docs/client/jmessage_android_guide.md'
    - 'SDK ErrorCode 定义': 'JMessage/docs/client/im_errorcode_android.md'
    - 'SDK API Doc': 'JMessage/docs/client/javadoc.md'
  - iOS:
    - 'SDK 开发指南': 'JMessage/docs/client/im_sdk_ios.md'
    - 'SDK 集成指南': 'JMessage/docs/client/jmessage_ios_guide.md'
    - 'SDK ErrorCode 定义': 'JMessage/docs/client/im_errorcode_ios.md'
    - 'SDK API Doc': 'JMessage/docs/client/iOSdoc.md'
  - Web:
    - 'Web SDK 开发指南 V2': 'JMessage/docs/client/im_sdk_js_v2.md'
    - 'Web SDK 开发指南': 'JMessage/docs/client/im_sdk_js.md'
    - '微信小程序 SDK': 'JMessage/docs/client/im_sdk_wxapplet.md'
    - 'SDK ErrorCode 定义': 'JMessage/docs/client/im_errorcode_js.md'
  - REST API:
    - 'REST API': 'JMessage/docs/server/rest_api_im.md'
    - 'REST Report V2': 'JMessage/docs/server/rest_api_im_report_v2.md'
    - 'REST Report': 'JMessage/docs/server/rest_api_im_report.md'
    - 'Server ErrorCode 定义': 'JMessage/docs/client/im_errorcode_server.md'
  - 高级:
    - '消息协议': 'JMessage/docs/advanced/im_message_protocol.md'
    - '业务对象': 'JMessage/docs/advanced/im_objects.md'
    - '实时消息路由': 'JMessage/docs/advanced/jmessage_callback.md'
  - 客户端集成插件: 'JMessage/docs/client/client_plugins.md'
  - 服务端 SDK:
    - 'Java SDK': 'JMessage/docs/server/sdk/java_sdk.md'
    - 'Python SDK': 'JMessage/docs/server/sdk/python_sdk.md'
    - 'PHP SDK': 'JMessage/docs/server/sdk/php_sdk.md'
    - 'C# SDK': 'JMessage/docs/server/sdk/csharp_sdk.md'
  - 最近更新: 'JMessage/docs/updates.md'
  - 资源下载: 'JMessage/docs/resources.md'

- JSMS:

  - 入门指南:
    - '短信验证码概述': 'JSMS/docs/guideline/JSMS_guide.md'
    - '控制台操作指南': 'JSMS/docs/guideline/JSMS_consoleguide.md'
  - Android:
    - 'Android SDK 概述': 'JSMS/docs/client/Android_SMS_SDK.md'
  - iOS:
    - 'iOS SDK 概述': 'JSMS/docs/client/iOS_SMS_SDK.md'
  - REST API:
    - 'REST API 概述': 'JSMS/docs/server/rest_api_jsms.md'
  - 最近更新: 'JSMS/docs/updates.md'
  - 资源下载: 'JSMS/docs/resources.md'

- JAnalytics:
  - 入门指南:
    - 'JAnalytics 产品简介': 'JAnalytics/docs/guideline/intro.md'
    - '常见问题': 'JAnalytics/docs/guideline/faq.md'
  - Android:
    - 'Android SDK 概述': 'JAnalytics/docs/client/android_sdk.md'
    - 'Android SDK 集成指南': 'JAnalytics/docs/client/android_guide.md'
    - 'Android SDK API': 'JAnalytics/docs/client/android_api.md'
  - iOS:
    - 'iOS SDK 概述': 'JAnalytics/docs/client/ios_sdk.md'
    - 'iOS SDK 集成指南': 'JAnalytics/docs/client/ios_guide.md'
    - 'iOS SDK API': 'JAnalytics/docs/client/ios_api.md'
  - 最近更新: 'JAnalytics/docs/updates.md'
  - 资源下载: 'JAnalytics/docs/resources.md'

- JShare:

  - 入门指南:
    - 'JShare 产品简介': 'JShare/docs/guideline/intro.md'
    - '第三方平台申请': 'JShare/docs/guideline/social_platform_apply.md'
    - '常见问题': 'JShare/docs/guideline/faq.md'
  - Android:
    - 'Android SDK 集成指南': 'JShare/docs/client/Android/android_sdk.md'
    - 'Android SDK API': 'JShare/docs/client/Android/android_api.md'
    - 'Android SDK FAQ': 'JShare/docs/client/Android/android_sdk_faq.md'
    - 'ErrorCode 定义': 'JShare/docs/client/Android/jshare_errorcode.md'
  - iOS:
    - 'iOS SDK 集成指南': 'JShare/docs/client/iOS/ios_sdk.md'
    - 'iOS SDK API': 'JShare/docs/client/iOS/ios_api.md'
    - 'iOS SDK FAQ': 'JShare/docs/client/iOS/ios_sdk_faq.md'
    - 'ErrorCode 定义': 'JShare/docs/client/iOS/jshare_errorcode.md'
  - 最近更新: 'JShare/docs/updates.md'
  - 资源下载: 'JShare/docs/resources.md'
