site_name: 极光推送文档
theme: bootstrap 

pages:
- [index.md, 首页]
- [dev_guides/faq.md, 开发指南, 常见问题]
- [dev_guides/android_guide.md, 开发指南, Android 集成指南]
- [dev_guides/ios_guide.md, 开发指南, iOS 集成指南]
- [dev_guides/winphone_guide.md, 开发指南, WinPhone 集成指南]
- [dev_guides/android_3m.md, 开发指南, 3 分钟快速集成 JPush Android SDK]
- [client_sdks/android_sdk.md, 客户端SDK, Andorid SDK]
- [client_sdks/android_tutorials.md, 客户端SDK, Andorid SDK 教程]
- [client_sdks/ios_sdk.md, 客户端SDK, iOS SDK]
- [client_sdks/ios_tutorials.md, 客户端SDK, iOS SDK 教程]
- [client_sdks/winphone_sdk.md, 客户端SDK, WinPhone SDK]
- [client_sdks/winphone_tutorials.md, 客户端SDK, WinPhone SDK 教程]
- [client_sdks/client_plugins.md, 客户端SDK, 客户端集成插件]
- [server_apis/server_sdks.md, REST API, 服务器端SDK]
- [server_apis/push_api_v3.md, REST API, Push API v3]
- [server_apis/push_api_v2.md, REST API, Push API v3]
- [server_apis/report_api_v3.md, REST API, Report API v3]
- [server_apis/api_rate_limiting.md, REST API, API 频率控制]
- [updates.md, 最近更新]
- [resouces.md, 资源下载]


